FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir streamlit chromadb openai python-dotenv scikit-learn sentence-transformers

COPY . /app

ENV PYTHONPATH="/app"

# Expose the Streamlit port
EXPOSE 8501

# Run app
CMD ["streamlit", "run", "ui/app.py"]
