name: SEC Edgar CI Pipeline

# When Should this pipeline run?
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: ["master" ]

# What computer should run this, and what should it do?
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Download code onto the GitHub server
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install uv
      - name: Setup uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "latest"
          enable-cache: true # makes CI run incredibly fast

      # Install Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Install dependencies
      - name: install Dependencies
        run: |
          uv venv
          uv pip install ruff bandit pytest unstructured

        # The Linter: Check for messy code and formatting errors
      - name: Lint with ruff
        run: |
          uv run ruff check .

      # Security Scanner:  Check for leaked API keys (Openrouter)
      - name: Security Scan with bandit
        run: |
          uv run bandit -r src/ -ll -c "bandit.yaml" || true # || true to not break if there is no bandit.yaml yet

      # The unit tests: test parsing logic
      - name: Run pytest
        run: |
          uv run pytest evals/test_parse.py

  publish-docker:
    needs: build-and-test # Wait for the tests to pass first
    runs-on: ubuntu-latest

    # Give the bot permission to upload warehouse
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Log in using the bot's temporary automatic password
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Force the repository the repository owner name into lowercase
    - name: Lowercase repository owner
      run: |
        echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
    
    # Build the Dockerfile and push it to the shelf
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/sec-edgar-ci-pipeline:latest